Jashan integrate auth design with networking
Lukauigi/COMP_4956_GAME_NAME_HERE pull request #4
Opened 2022-11-07 04:33 UTC by JashanpreetSingh-dev

I have integrated my auth code with the design team's Scenes

2022-11-08 22:27 UTC, gabeBaluyut commented on Assets/Scripts/Authentication/SignUpUI.cs
>      public void CreateAccount()
Add comment for function

2022-11-08 22:28 UTC, gabeBaluyut commented on Assets/Scripts/Authentication/AccountManager.cs
Insert header file for tracking date, version, etc.

2022-11-08 22:29 UTC, gabeBaluyut commented on Assets/Scripts/Authentication/AccountManager.cs
>      /// <param name="Username"> a string </param>
Insert function comment

2022-11-08 22:39 UTC, gabeBaluyut requested changes
Add header comment for file and functions, otherwise good

2022-11-10 21:06 UTC, closed without merging

2022-11-10 21:06 UTC, JashanpreetSingh-dev commented
Making a new pull request